#services:
#  redis:
#    image: redis:latest
#    container_name: redis-server
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./redis:/var/lib/redis